DOMAIN = "multi_sun"

ATTR_SUNS = "suns"
ATTR_CITY = "city"
ATTR_LAT = "latitude"
ATTR_LONG = "longitude"
ATTR_OFFSET_DATE_UNITS = "days_offset"
ATTR_OFFSET_DATE_VALUE = "days_offset_value"
ATTR_OFFSET_TIME_UNITS = "time_offset"
ATTR_OFFSET_TIME_VALUE = "time_offset_value"
ATTR_SUNRISE = "sunrise"
ATTR_SUNSET = "sunset"
ATTR_HOURS_IN_DAY = "hours_in_day"
ATTR_TIMEZONE = "timezone"
DEFAULT_OFFSET_DATE_UNIT = "days"
DEFAULT_OFFSET_TIME_UNIT = "seconds"
DEFAULT_SCAN_INTERVAL = 61